CREATE PROCEDURE SEARCHTABLEAGENT3 @CITY CHAR(35)
AS
SELECT *
FROM AGENTS
WHERE AGENT_CODE IN
		(SELECT AGENT_CODE FROM CUSTOMER
		WHERE AGENTS.WORKING_AREA =@CITY);
Go

EXEC SEARCHTABLEAGENT3 @CITY = 'London';