CREATE TABLE EMPLOYEE1
(
EID INT IDENTITY,
ENAME VARCHAR(200),
ESALARY INT,
ESTATE VARCHAR(50)
);


INSERT INTO EMPLOYEE1 
VALUES
('Govinda',25000,'MH'),
('Dinesh',20000,'MH'),
('Pranav',23000,'MH'),
('Anand',21000,'MH');

SELECT * FROM EMPLOYEE1;
INSERT INTO EMPLOYEE1 
VALUES
('Gov',15000,'MH');

--DECLARE @AVGSALARY float;
--select AVG(ESALARY) FROM EMPLOYEE1;
